/******
HISTORY
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RHI_TRACKED_CHANGE_RECORD')
	CREATE CLUSTERED INDEX [CIX_RHI_TRACKED_CHANGE_RECORD] ON [dbo].[RHI_TRACKED_CHANGE_RECORD] ([RHI_TCH_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RHI_ENTITY_ATTRIBUTE_DATA')
	CREATE CLUSTERED INDEX [CIX_RHI_ENTITY_ATTRIBUTE_DATA] ON [dbo].[RHI_ENTITY_ATTRIBUTE_DATA] ([RHI_EAD_Ordinal]);
GO
