/******
NOTIFICATIONS
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_NOTIFICATION_BUFFER')
	CREATE CLUSTERED INDEX [CIX_RNO_NOTIFICATION_BUFFER] ON [dbo].[RNO_NOTIFICATION_BUFFER] ([RNO_NBF_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_BUFFERED_NOTIFICATION')
	CREATE CLUSTERED INDEX [CIX_RNO_BUFFERED_NOTIFICATION] ON [dbo].[RNO_BUFFERED_NOTIFICATION] ([RNO_BNT_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_APNS_USER_DEVICE_TOKEN')
	CREATE CLUSTERED INDEX [CIX_RNO_APNS_USER_DEVICE_TOKEN] ON [dbo].[RNO_APNS_USER_DEVICE_TOKEN] ([RNO_AUT_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_APNS_EXTERNAL_USER_DEVICE_TOKEN')
	CREATE CLUSTERED INDEX [CIX_RNO_APNS_EXTERNAL_USER_DEVICE_TOKEN] ON [dbo].[RNO_APNS_EXTERNAL_USER_DEVICE_TOKEN] ([RNO_AET_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_FCM_USER_DEVICE_TOKEN')
	CREATE CLUSTERED INDEX [CIX_RNO_FCM_USER_DEVICE_TOKEN] ON [dbo].[RNO_FCM_USER_DEVICE_TOKEN] ([RNO_FUT_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RNO_FCM_EXTERNAL_USER_DEVICE_TOKEN')
	CREATE CLUSTERED INDEX [CIX_RNO_FCM_EXTERNAL_USER_DEVICE_TOKEN] ON [dbo].[RNO_FCM_EXTERNAL_USER_DEVICE_TOKEN] ([RNO_FET_Ordinal]);
GO
