IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'GTC_ROLE_X_PERMISSION' AND COLUMN_NAME = 'GTC_ROP_ResourceId')
BEGIN
	EXEC sp_RENAME 'GTC_ROLE_X_PERMISSION.GTC_ROP_ContextId' , 'GTC_ROP_ResourceId', 'COLUMN';
	ALTER TABLE GTC_ROLE_X_PERMISSION ADD [GTC_ROP_ContextId] [UNIQUEIDENTIFIER];
END;
GO