IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REX_TODO')
CREATE TABLE [dbo].[REX_TODO] (
	[REX_TOD_TodoId] [UNIQUEIDENTIFIER] NOT NULL,
	[REX_TOD_Ordinal] [INT] IDENTITY(1,1),
	[REX_TOD_Version] [INT] NOT NULL,
	[REX_TOD_Title] [NVARCHAR](MAX),
	CONSTRAINT [REX_TODO_PK] PRIMARY KEY NONCLUSTERED ([REX_TOD_TodoId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_REX_TODO')
	CREATE CLUSTERED INDEX CIX_REX_TODO ON [dbo].[REX_TODO]([REX_TOD_Ordinal])
GO
