/******
EVENT STORE
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RES_EVENT_STREAM')
CREATE TABLE [dbo].[RES_EVENT_STREAM] (
	[RES_EVS_EventStreamId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_EVS_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[RES_EVS_Version] [INT] NOT NULL,
	[RES_EVS_MetadataJson] [NVARCHAR] (MAX),
	CONSTRAINT [RES_EVENT_STREAM_PK] PRIMARY KEY NONCLUSTERED ([RES_EVS_EventStreamId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'RES_EVENT_STREAM_ROW')
CREATE TABLE [dbo].[RES_EVENT_STREAM_ROW] (
	[RES_EVR_EventStreamRowId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_EVR_GlobalSequenceNumber] [INT] IDENTITY(1,1) NOT NULL,
	[RES_EVR_StreamId] [UNIQUEIDENTIFIER] NOT NULL,
	[RES_EVR_StreamSequenceNumber] [BIGINT] NOT NULL,
	[RES_EVR_DatePublished] [DATETIMEOFFSET] NOT NULL,
	[RES_EVR_EventJson] [NVARCHAR] (MAX) NULL,
	[RES_EVR_AdditionalMetadataJson] [NVARCHAR] (MAX) NULL
	CONSTRAINT [RES_EVENT_STREAM_ROW_PK] PRIMARY KEY NONCLUSTERED ([RES_EVR_EventStreamRowId]),
	CONSTRAINT [RES_EVENT_STREAM_ROW_FK_EVENT_STREAM] FOREIGN KEY ([RES_EVR_StreamId]) REFERENCES [dbo].[RES_EVENT_STREAM] ([RES_EVS_EventStreamId]),
	CONSTRAINT [RES_EVENT_STREAM_ROW_UK_EVENT_STREAM_ID_AND_STREAM_SEQUENCE_NUMBER] UNIQUE([RES_EVR_StreamId], [RES_EVR_StreamSequenceNumber])
);
GO

/******
HISTORY
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_TRACKED_CHANGE_RECORD')
CREATE TABLE [dbo].[REV_TRACKED_CHANGE_RECORD] (
	[REV_TCH_TrackedChangeRecordId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_TCH_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_TCH_ActorName] [NVARCHAR] (MAX) NOT NULL,
	[REV_TCH_UserId] [UNIQUEIDENTIFIER],
	[REV_TCH_AggregateId] [UNIQUEIDENTIFIER],
	[REV_TCH_AggregateClassId] [UNIQUEIDENTIFIER],
	[REV_TCH_EntityId] [UNIQUEIDENTIFIER],
	[REV_TCH_EntityClassId] [UNIQUEIDENTIFIER],
	[REV_TCH_ChangeTime] [DATETIME] NOT NULL,
	[REV_TCH_ChangeDataJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_TCH_ChangeDataClassName] [NVARCHAR] (MAX) NOT NULL,
	CONSTRAINT [REV_TRACKED_CHANGE_RECORD_PK] PRIMARY KEY NONCLUSTERED ([REV_TCH_TrackedChangeRecordId])/*,
	CONSTRAINT [REV_TRACKED_CHANGE_RECORD_FK_USERID] FOREIGN KEY ([REV_TCH_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_ENTITY_ATTRIBUTE_DATA')
CREATE TABLE [dbo].[REV_ENTITY_ATTRIBUTE_DATA] (
	[REV_EAD_EntityAttributeDataId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_EAD_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_EAD_AggregateId] [UNIQUEIDENTIFIER],
	[REV_EAD_EntityId] [UNIQUEIDENTIFIER],
	[REV_EAD_AttributeValueMapJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_EAD_Version] [INT] NOT NULL,
	CONSTRAINT [REV_ENTITY_ATTRIBUTE_DATA_PK] PRIMARY KEY NONCLUSTERED ([REV_EAD_EntityAttributeDataId])
);
GO

/******
NOTIFICATIONS
******/

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_NOTIFICATION_BUFFER')
CREATE TABLE [dbo].[REV_NOTIFICATION_BUFFER] (
	[REV_NBF_NotificationBufferId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_NBF_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_NBF_PipelineId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_NBF_GovernorId] [UNIQUEIDENTIFIER] NOT NULL
	CONSTRAINT [REV_NOTIFICATION_BUFFER_PK] PRIMARY KEY NONCLUSTERED ([REV_NBF_NotificationBufferId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_BUFFERED_NOTIFICATION')
CREATE TABLE [dbo].[REV_BUFFERED_NOTIFICATION] (
	[REV_BNT_BufferedNotificationId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_BNT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_BNT_NotificationClassName] [NVARCHAR] (MAX) NOT NULL,
	[REV_BNT_NotificationJson] [NVARCHAR] (MAX) NOT NULL,
	[REV_BNT_BufferId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_BNT_TimeQueued] [DATETIME] NOT NULL
	CONSTRAINT [REV_BUFFERED_NOTIFICATION_PK] PRIMARY KEY NONCLUSTERED ([REV_BNT_BufferedNotificationId]),
	CONSTRAINT [REV_BUFFERED_NOTIFICATION_FK_BUFFERID] FOREIGN KEY ([REV_BNT_BufferId]) REFERENCES [dbo].[REV_NOTIFICATION_BUFFER] ([REV_NBF_NotificationBufferId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_APNS_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_APNS_USER_DEVICE_TOKEN] (
	[REV_AUT_ApnsUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AUT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_AUT_Version] [INT] NOT NULL,
	[REV_AUT_UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AUT_DeviceToken] [NVARCHAR] (MAX) NOT NULL,
	[REV_AUT_AppId] [VARCHAR] (255) NOT NULL,
	[REV_AUT_IssuedDateTime] [DATETIME] NOT NULL
	CONSTRAINT [REV_APNS_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_AUT_ApnsUserDeviceTokenId])/*,
	CONSTRAINT [REV_APNS_USER_DEVICE_TOKEN_FK_USERID] FOREIGN KEY ([REV_AUT_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_APNS_EXTERNAL_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_APNS_EXTERNAL_USER_DEVICE_TOKEN] (
	[REV_AET_ApnsExternalUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AET_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_AET_Version] [INT] NOT NULL,
	[REV_AET_ExternalUserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_AET_DeviceToken] [NVARCHAR] (MAX) NOT NULL,
	[REV_AET_AppId] [VARCHAR] (255) NOT NULL,
	[REV_AET_IssuedDateTime] [DATETIME] NOT NULL
	CONSTRAINT [REV_APNS_EXTERNAL_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_AET_ApnsExternalUserDeviceTokenId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_FCM_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_FCM_USER_DEVICE_TOKEN] (
	[REV_FUT_FcmUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FUT_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_FUT_Version] [INT] NOT NULL,
	[REV_FUT_UserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FUT_RegistrationId] [NVARCHAR] (MAX) NOT NULL,
	[REV_FUT_AppId] [VARCHAR] (255) NOT NULL,
	[REV_FUT_IssuedDateTime] [DATETIME] NOT NULL
	CONSTRAINT [REV_FCM_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_FUT_FcmUserDeviceTokenId])/*,
	CONSTRAINT [REV_FCM_USER_DEVICE_TOKEN_FK_USERID] FOREIGN KEY ([REV_FUT_UserId]) REFERENCES [dbo].[GT_USER] ([GT_USR_UserId])*/
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_FCM_EXTERNAL_USER_DEVICE_TOKEN')
CREATE TABLE [dbo].[REV_FCM_EXTERNAL_USER_DEVICE_TOKEN] (
	[REV_FET_FcmExternalUserDeviceTokenId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FET_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_FET_Version] [INT] NOT NULL,
	[REV_FET_ExternalUserId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_FET_RegistrationId] [NVARCHAR] (MAX) NOT NULL,
	[REV_FET_AppId] [VARCHAR] (255) NOT NULL,
	[REV_FET_IssuedDateTime] [DATETIME] NOT NULL
	CONSTRAINT [REV_FCM_EXTERNAL_USER_DEVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_FET_FcmExternalUserDeviceTokenId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_LOCALIZATION_MESSAGE')
CREATE TABLE [dbo].[REV_LOCALIZATION_MESSAGE] (
	[REV_LOM_LocalizationMessageId] [UNIQUEIDENTIFIER],
	[REV_LOM_Ordinal] [INT] IDENTITY(1,1),
	[REV_LOM_Version] [INT] NOT NULL,
	[REV_LOM_TenantId] [UNIQUEIDENTIFIER],
	[REV_LOM_ClassName] [VARCHAR](1024) NOT NULL,
	[REV_LOM_Key] [NVARCHAR](255) NOT NULL,
	[REV_LOM_Message] [NVARCHAR](MAX),
	[REV_LOM_LocaleCode] [VARCHAR](128) NOT NULL,
	CONSTRAINT [REV_LOCALIZATION_MESSAGE_PK] PRIMARY KEY NONCLUSTERED ([REV_LOM_LocalizationMessageId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_SERVICE_TOKEN')
CREATE TABLE [dbo].[REV_SERVICE_TOKEN] (
	[REV_SRT_ServiceTokenId] [UNIQUEIDENTIFIER],
	[REV_SRT_Ordinal] [INT] IDENTITY(1,1),
	[REV_SRT_Version] [INT],
	[REV_SRT_ServiceName] [NVARCHAR](512) NOT NULL,
	[REV_SRT_Timestamp] [DATETIME] DEFAULT GETDATE()
	CONSTRAINT [REV_SERVICE_TOKEN_PK] PRIMARY KEY NONCLUSTERED ([REV_SRT_ServiceTokenId])
);
GO