IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_DOMAIN_AGGREGATE_RECORD')
CREATE TABLE [dbo].[REV_DOMAIN_AGGREGATE_RECORD] (
	[REV_DAR_DomainAggregateRecordId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_DAR_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_DAR_ClassId] [UNIQUEIDENTIFIER] NOT NULL,
	CONSTRAINT [REV_DOMAIN_AGGREGATE_RECORD_PK] PRIMARY KEY NONCLUSTERED ([REV_DAR_DomainAggregateRecordId])
);
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'REV_DOMAIN_EVENT_PACKET')
CREATE TABLE [dbo].[REV_DOMAIN_EVENT_PACKET] (
	[REV_DEP_DomainEventPacketId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_DEP_Ordinal] [INT] IDENTITY(1,1) NOT NULL,
	[REV_DEP_AggregateId] [UNIQUEIDENTIFIER] NOT NULL,
	[REV_DEP_SequenceNumber] [INT] NOT NULL,
	[REV_DEP_ActorName] [VARCHAR] (255) NULL,
	[REV_DEP_DatePublished] [DATETIME] NOT NULL,
	[REV_DEP_EventsJson] [NVARCHAR] (MAX) NULL
	CONSTRAINT [REV_DOMAIN_EVENT_PACKET_PK] PRIMARY KEY NONCLUSTERED ([REV_DEP_DomainEventPacketId]),
	CONSTRAINT [REV_DOMAIN_EVENT_PACKET_FK_AGGREGATE] FOREIGN KEY ([REV_DEP_AggregateId]) REFERENCES [dbo].[REV_DOMAIN_AGGREGATE_RECORD] ([REV_DAR_DomainAggregateRecordId]),
	CONSTRAINT [REV_DOMAIN_EVENT_PACKET_UK_AGGREGATE_ID_AND_SEQUENCE_NUMBER] UNIQUE([REV_DEP_AggregateId], [REV_DEP_SequenceNumber])
);
GO

/* TODO: indexes */