/******
EVENT STORE
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM')
	CREATE CLUSTERED INDEX [CIX_RES_EVENT_STREAM] ON [dbo].[RES_EVENT_STREAM] ([RES_EVS_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM_ROW')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RES_EVENT_STREAM_ROW] ON [dbo].[RES_EVENT_STREAM_ROW] ([RES_EVR_GlobalSequenceNumber]);
GO

/*** TODO ***/
