/******
EVENT STORE
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM')
	CREATE CLUSTERED INDEX [CIX_RES_EVENT_STREAM] ON [dbo].[RES_EVENT_STREAM] ([RES_EVS_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RES_EVENT_STREAM_ROW')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RES_EVENT_STREAM_ROW] ON [dbo].[RES_EVENT_STREAM_ROW] ([RES_ESR_GlobalSequenceNumber]);
GO

/******
ASYNC EVENTS
******/

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_ASYNC_EVENT_QUEUE')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_ASYNC_EVENT_QUEUE] ON [dbo].[RAE_ASYNC_EVENT_QUEUE] ([RAE_AEQ_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_EXTERNAL_EVENT_RECORD')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_EXTERNAL_EVENT_RECORD] ON [dbo].[RAE_EXTERNAL_EVENT_RECORD] ([RAE_EER_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'CIX_RAE_QUEUED_ASYNC_EVENT')
	CREATE UNIQUE CLUSTERED INDEX [CIX_RAE_QUEUED_ASYNC_EVENT] ON [dbo].[RAE_QUEUED_ASYNC_EVENT] ([RAE_QAE_Ordinal]);
GO

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UIX_RAE_QUEUED_ASYNC_EVENT')
	CREATE UNIQUE NONCLUSTERED INDEX [UIX_RAE_QUEUED_ASYNC_EVENT] ON [dbo].[RAE_QUEUED_ASYNC_EVENT] ([RAE_QAE_QueueId], [RAE_QAE_SequenceNumber]) WHERE [RAE_QAE_SequenceNumber] IS NOT NULL;
GO

/*** TODO ***/
